---
- name: Check demo directory
  file:
    path: '{{ demo_path }}'
    state: directory
    mode: 0755

- name: Setup demo service
  template:
    src: '{{ item }}'
    dest: '{{ demo_path }}/{{ item }}'
    mode: 0644
  with_items:
    - backend-svc.yaml
    - frontend-svc.yaml
    - backend-rc.yaml
    - frontend-rc.yaml
    - busybox.yaml
