apiVersion: v1
kind: ReplicationController
metadata:
  name: webdb-controller
spec:
  replicas: 1
  selector:
    name: webdb
  template:
    metadata:
      name: webdb
      labels:
        name: webdb
    spec:
      containers:
        - name: webdb
          image: "webdb:0.1"
          ports:
            - containerPort: 3306

