---
- hosts: datastore
  tasks:
    - ping:
- hosts: master
  tasks:
    - ping:
- hosts: node
  tasks:
    - ping:

- hosts: datastore
  pre_tasks:
  - set_fact:
      master_ipv4: "{{ groups['master']|map('extract', hostvars, 'ansible_all_ipv4_addresses')|map(attribute='0')|list }}"
      master_ipv6: "{{ groups['master']|map('extract', hostvars, 'ansible_all_ipv6_addresses')|map(attribute='0')|list }}"
      nodes_ipv4: "{{ groups['node']|map('extract', hostvars, 'ansible_all_ipv4_addresses')|map(attribute='0')|list }}"
      nodes_ipv6: "{{ groups['node']|map('extract', hostvars, 'ansible_all_ipv6_addresses')|map(attribute='0')|list }}"
  roles:
    - role: config
      tags: config

- hosts: master
  pre_tasks:
  - set_fact:
      datastore_host: "{{ groups['datastore'][0] | default('0.0.0.0') }}"
      nodes_ipv4: "{{ groups['node']|map('extract', hostvars, 'ansible_all_ipv4_addresses')|map(attribute='0')|list }}"
      nodes_ipv6: "{{ groups['node']|map('extract', hostvars, 'ansible_all_ipv6_addresses')|map(attribute='0')|list }}"
  roles:
    - role: flannel
      tags: flannel
    - role: k8s-master
      tags: k8s-master

- hosts: node
  pre_tasks:
  - set_fact:
      datastore_host: "{{ groups['datastore'][0] | default('0.0.0.0') }}"
      master_host: "{{ groups['master'][0] | default('0.0.0.0') }}"
      master_ipv4: "{{ groups['master']|map('extract', hostvars, 'ansible_all_ipv4_addresses')|map(attribute='0')|list }}"
      master_ipv6: "{{ groups['master']|map('extract', hostvars, 'ansible_all_ipv6_addresses')|map(attribute='0')|list }}"
      nodes_ipv4: "{{ groups['node']|map('extract', hostvars, 'ansible_all_ipv4_addresses')|map(attribute='0')|list }}"
      nodes_ipv6: "{{ groups['node']|map('extract', hostvars, 'ansible_all_ipv6_addresses')|map(attribute='0')|list }}"
  roles:
    - role: flannel
      tags: flannel
    - role: k8s-node
      tags: k8s-node
