apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ demo_backend_name }}
  name: {{ demo_backend_name }}
  namespace: {{ demo_namespace }}
spec:
  ports:
    - port: {{ demo_backend_port }}
  selector:
    name: {{ demo_backend_name }}

