apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ demo_frontend_name }}
  name: {{ demo_frontend_name }}
  namespace: {{ demo_namespace }}
spec:
  ports:
    - port: {{ demo_frontend_port }}
  selector:
    name: {{ demo_frontend_name }}
  externalIPs: [{{ demo_ipv4 | join(', ') }}]
