---
- name: Setup firewall ports
  firewalld:
    zone: trusted
    port: "{{ item }}"
    state: enabled
    permanent: true
  with_items:
    - 8080/tcp
  notify:
    - reload firewall

- name: Setup firewall interfaces
  firewalld:
    zone: trusted
    interface: "{{ item }}"
    state: enabled
    permanent: true
  with_items:
    - docker+
    - flannel.+
  notify:
    - reload firewall

- name: Setup firewall sources
  firewalld:
    zone: trusted
    source: "{{ item }}"
    state: enabled
    permanent: true
  with_items:
    - '{{ nodes_ipv4 }}'
    - '{{ nodes_ipv6 }}'
  notify:
    - reload firewall

- name: Install Kubernets Master
  yum:
    name: kubernetes
    state: present

- name: Pull Kubernetes images
  docker_image:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
  with_items:
    - { name: "{{ k8s_master_pod_infra_image }}", tag: "{{ k8s_master_pod_infra_image_tag }}" }
    - { name: "{{ k8s_master_api_server_image }}", tag: "{{ k8s_master_api_server_image_tag }}" }
    - { name: "{{ k8s_master_controller_mgr_image }}", tag: "{{ k8s_master_controller_mgr_image_tag }}" }
    - { name: "{{ k8s_master_scheduler_image }}", tag: "{{ k8s_master_scheduler_image_tag }}" }
    - { name: "{{ k8s_master_kubedns_image }}", tag: "{{ k8s_master_kubedns_image_tag }}" }
    - { name: "{{ k8s_master_dnsmasq_image }}", tag: "{{ k8s_master_dnsmasq_image_tag }}" }
    - { name: "{{ k8s_master_healthz_image }}", tag: "{{ k8s_master_healthz_image_tag }}" }

- name: Enable Kubernetes services
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - kubelet
    - kube-proxy

- name: Check kubernetes configs directories
  file:
    path: '{{ k8s_master_config }}/{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - manifests
    - addon

- name: Setup Kubelet service
  template:
    src: kubelet.j2
    dest: '{{ k8s_master_config }}/kubelet'
    mode: 0644
  notify:
    - restart kube-proxy/kubelet

- name: Register API Server
  template:
    src: apiserver.pod.json.j2
    dest: '{{ k8s_master_config }}/manifests/apiserver.pod.json'
    mode: 0644
  notify:
    - restart kube-proxy/kubelet

- name: Register Controller Manager
  template:
    src: controller-manager.pod.json.j2
    dest: '{{ k8s_master_config }}/manifests/controller-manager.pod.json'
    mode: 0644
  notify:
    - restart kube-proxy/kubelet

- name: Register Scheduler
  template:
    src: scheduler.pod.json.j2
    dest: '{{ k8s_master_config }}/manifests/scheduler.pod.json'
    mode: 0644
  notify:
    - restart kube-proxy/kubelet

- name: Setup addon services
  template:
    src: "{{ item }}"
    dest: '{{ k8s_master_config }}/addon/{{ item }}'
    mode: 0644
  with_items:
    - kubedns-svc.yaml
    - kubedns-rc.yaml
