galaxy_info:
  author: Igor Dolzhikov
  description: Cluster configuration
  company: Openprovider

  license: license (MIT)

  min_ansible_version: 2.1

  platforms:
  - name: EL
    versions:
    - 7

  galaxy_tags: ["config"]

dependencies:
  - role: etcd